server:
  port: 9000

spring:
  security:
    oauth2:
      authorization-server:
        issuer-uri: http://localhost:9000

server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.same-site=strict
