server:
  port: 9000
  servlet:
    session:
      cookie:
        http-only: true
        secure: true
        same-site: strict

spring:
  security:
    oauth2:
      authorization-server:
        issuer-uri: http://localhost:9000
